project:
  version: 1.0.0
  name: 'maiden'
  install_requires: 
    - 'click'
    - 'pyyaml'
    - 'jinja2'
more:
  author: 'Huseyin Gomleksizoglu'
  author_email: 'huseyim@gmail.com'
  description: 'A tool to generate Markdown files from templates populated with data from YAML or JSON files.'
  long_description: open('README.md').read()
  long_description_content_type: 'text/markdown'
  url: 'https://github.com/gomleksiz/maiden'
  python_requires: '>: 3.6'


